#!/usr/bin/env bash
# Pi-hole Web UI Localization Script (Simplified Chinese)

WEB_DIR="${1:-/var/www/html/admin}"

if [ ! -d "$WEB_DIR" ]; then
    echo "Web directory $WEB_DIR does not exist."
    exit 1
fi

echo "Localizing Web UI in $WEB_DIR..."

# Helper function for sed replacement
replace_str() {
    local file="$1"
    local search="$2"
    local replace="$3"
    if [ -f "$file" ]; then
        sed -i "s|${search}|${replace}|g" "$file"
    fi
}

# --- Sidebar ---
SIDEBAR="$WEB_DIR/scripts/lua/sidebar.lp"
replace_str "$SIDEBAR" "<span>Dashboard</span>" "<span>仪表板</span>"
replace_str "$SIDEBAR" "<span>Login</span>" "<span>登录</span>"
replace_str "$SIDEBAR" "<span>Logout</span>" "<span>注销</span>"
replace_str "$SIDEBAR" "<span>Query Log</span>" "<span>查询日志</span>"
replace_str "$SIDEBAR" "<span>Long-term data</span>" "<span>长期数据</span>"
replace_str "$SIDEBAR" "<span>Graphics</span>" "<span>图表</span>"
replace_str "$SIDEBAR" "<span>Query Lists</span>" "<span>查询列表</span>"
replace_str "$SIDEBAR" "<span>Top Lists</span>" "<span>热门列表</span>"
replace_str "$SIDEBAR" "<span>Groups</span>" "<span>群组</span>"
replace_str "$SIDEBAR" "<span>Clients</span>" "<span>客户端</span>"
replace_str "$SIDEBAR" "<span>Domains</span>" "<span>域名</span>"
replace_str "$SIDEBAR" "<span>Adlists</span>" "<span>广告列表</span>"
replace_str "$SIDEBAR" "Disable Blocking" "禁用拦截"
replace_str "$SIDEBAR" "Enable Blocking" "启用拦截"
replace_str "$SIDEBAR" "For 10 seconds" "10 秒"
replace_str "$SIDEBAR" "For 30 seconds" "30 秒"
replace_str "$SIDEBAR" "For 5 minutes" "5 分钟"
replace_str "$SIDEBAR" "Custom time" "自定义时间"
replace_str "$SIDEBAR" "<span>System</span>" "<span>系统</span>"
replace_str "$SIDEBAR" "<span>Settings</span>" "<span>设置</span>"
replace_str "$SIDEBAR" "<span>Tools</span>" "<span>工具</span>"
replace_str "$SIDEBAR" "<span>Pi-hole diagnosis</span>" "<span>Pi-hole 诊断</span>"
replace_str "$SIDEBAR" "<span>Tail log files</span>" "<span>实时日志</span>"
replace_str "$SIDEBAR" "<span>Update Gravity</span>" "<span>更新 Gravity</span>"
replace_str "$SIDEBAR" "<span>Search Lists</span>" "<span>搜索列表</span>"
replace_str "$SIDEBAR" "<span>Interfaces</span>" "<span>接口</span>"
replace_str "$SIDEBAR" "<span>Network</span>" "<span>网络</span>"
replace_str "$SIDEBAR" "<span>Donate</span>" "<span>捐赠</span>"
replace_str "$SIDEBAR" "<span>Local DNS Records</span>" "<span>本地 DNS 记录</span>"
replace_str "$SIDEBAR" "<span>DNS</span>" "<span>DNS</span>"
replace_str "$SIDEBAR" "<span>DHCP</span>" "<span>DHCP</span>"
replace_str "$SIDEBAR" "<span>Web interface / API</span>" "<span>Web 界面 / API</span>"
replace_str "$SIDEBAR" "<span>Privacy</span>" "<span>隐私</span>"
replace_str "$SIDEBAR" "<span>Teleporter</span>" "<span>传送门 (Teleporter)</span>"
replace_str "$SIDEBAR" "<span>All settings</span>" "<span>所有设置</span>"

# --- Dashboard (index.lp) ---
INDEX="$WEB_DIR/index.lp"
replace_str "$INDEX" "<p>Total queries</p>" "<p>总查询</p>"
replace_str "$INDEX" "<p>Queries Blocked</p>" "<p>已拦截查询</p>"
replace_str "$INDEX" "<p>Percentage Blocked</p>" "<p>拦截百分比</p>"
replace_str "$INDEX" "<p>Domains on Lists</p>" "<p>列表中的域名</p>"
replace_str "$INDEX" "List blocked queries" "列出已拦截的查询"
replace_str "$INDEX" "List all queries" "列出所有查询"
replace_str "$INDEX" "Manage lists" "管理列表"
replace_str "$INDEX" "active clients" "活跃客户端"
replace_str "$INDEX" "<h3 class=\"box-title\">Total queries</h3>" "<h3 class=\"box-title\">总查询</h3>"
replace_str "$INDEX" "<h3 class=\"box-title\">Client activity</h3>" "<h3 class=\"box-title\">客户端活动</h3>"
replace_str "$INDEX" "<h3 class=\"box-title\">Query Types</h3>" "<h3 class=\"box-title\">查询类型</h3>"
replace_str "$INDEX" "<h3 class=\"box-title\">Upstream servers</h3>" "<h3 class=\"box-title\">上游服务器</h3>"
replace_str "$INDEX" "<h3 class=\"box-title\">Top Permitted Domains</h3>" "<h3 class=\"box-title\">热门允许域名</h3>"
replace_str "$INDEX" "<h3 class=\"box-title\">Top Blocked Domains</h3>" "<h3 class=\"box-title\">热门拦截域名</h3>"
replace_str "$INDEX" "<h3 class=\"box-title\">Top Clients (total)</h3>" "<h3 class=\"box-title\">热门客户端 (总计)</h3>"
replace_str "$INDEX" "<h3 class=\"box-title\">Top Clients (blocked only)</h3>" "<h3 class=\"box-title\">热门客户端 (仅拦截)</h3>"
replace_str "$INDEX" "Reset zoom" "重置缩放"
replace_str "$INDEX" "<th>Domain</th>" "<th>域名</th>"
replace_str "$INDEX" "<th>Hits</th>" "<th>命中</th>"
replace_str "$INDEX" "<th>Frequency</th>" "<th>频率</th>"
replace_str "$INDEX" "<th>Client</th>" "<th>客户端</th>"
replace_str "$INDEX" "<th>Requests</th>" "<th>请求</th>"

# --- Queries (queries.lp) ---
QUERIES="$WEB_DIR/queries.lp"
replace_str "$QUERIES" "<h3 class=\"box-title\">Query Log</h3>" "<h3 class=\"box-title\">查询日志</h3>"

# --- Groups (groups.lp) ---
GROUPS="$WEB_DIR/groups.lp"
replace_str "$GROUPS" "<h3 class=\"box-title\">Group management</h3>" "<h3 class=\"box-title\">组管理</h3>"
replace_str "$GROUPS" "<h1>Group management</h1>" "<h1>组管理</h1>"
replace_str "$GROUPS" "Add a new group" "添加新组"
replace_str "$GROUPS" "List of groups" "组列表"
replace_str "$GROUPS" "<label for=\"new_name\">Name:</label>" "<label for=\"new_name\">名称:</label>"
replace_str "$GROUPS" "placeholder=\"Group name\"" "placeholder=\"组名\""
replace_str "$GROUPS" "<label for=\"new_comment\">Comment:</label>" "<label for=\"new_comment\">备注:</label>"
replace_str "$GROUPS" "placeholder=\"Group comment (optional)\"" "placeholder=\"组备注 (可选)\""
replace_str "$GROUPS" "<strong>Hints:</strong>" "<strong>提示:</strong>"
replace_str "$GROUPS" "<li>Multiple groups can be added by separating each group name with a space or comma</li>" "<li>可以通过空格或逗号分隔每个组名来添加多个组</li>"
replace_str "$GROUPS" "<li>Group names can have spaces if entered in quotes. e.g \"My New Group\"</li>" "<li>如果组名包含空格，请使用引号括起来，例如 \"My New Group\"</li>"
replace_str "$GROUPS" ">Add</button>" ">添加</button>"
replace_str "$GROUPS" "<th>Name</th>" "<th>名称</th>"
replace_str "$GROUPS" "<th>Status</th>" "<th>状态</th>"
replace_str "$GROUPS" "<th>Comment</th>" "<th>备注</th>"
replace_str "$GROUPS" "Reset sorting" "重置排序"

# --- Group Lists (groups-lists.lp) ---
GROUPS_LISTS="$WEB_DIR/groups-lists.lp"
replace_str "$GROUPS_LISTS" "<h1>Subscribed lists group management</h1>" "<h1>订阅列表组管理</h1>"
replace_str "$GROUPS_LISTS" "Add a new subscribed list" "添加新的订阅列表"
replace_str "$GROUPS_LISTS" "Subscribed lists" "订阅列表"
replace_str "$GROUPS_LISTS" "<label for=\"new_address\">Address:</label>" "<label for=\"new_address\">地址:</label>"
replace_str "$GROUPS_LISTS" "<label for=\"new_comment\">Comment:</label>" "<label for=\"new_comment\">备注:</label>"
replace_str "$GROUPS_LISTS" "placeholder=\"List description (optional)\"" "placeholder=\"列表描述 (可选)\""
replace_str "$GROUPS_LISTS" "<label for=\"new_group\">Group assignment:</label>" "<label for=\"new_group\">组分配:</label>"
replace_str "$GROUPS_LISTS" "<strong>Hints:</strong>" "<strong>提示:</strong>"
replace_str "$GROUPS_LISTS" "Please run <code>pihole -g</code> or update your gravity list <a href=\"<?=webhome?>gravity\">online</a> after modifying your lists." "修改列表后，请运行 <code>pihole -g</code> 或 <a href=\"<?=webhome?>gravity\">在线</a> 更新您的 Gravity 列表。"
replace_str "$GROUPS_LISTS" "Multiple lists can be added by separating each <em>unique</em> URL with a space or comma" "可以通过空格或逗号分隔每个 <em>唯一</em> URL 来添加多个列表"
replace_str "$GROUPS_LISTS" "Click on the icon in the first column to get additional information about your lists. The icons correspond to the health of the list." "点击第一列的图标以获取有关列表的更多信息。图标对应列表的健康状况。"
replace_str "$GROUPS_LISTS" "Add blocklist" "添加拦截列表"
replace_str "$GROUPS_LISTS" "Add allowlist" "添加允许列表"
replace_str "$GROUPS_LISTS" "<th>Address</th>" "<th>地址</th>"
replace_str "$GROUPS_LISTS" "<th>Status</th>" "<th>状态</th>"
replace_str "$GROUPS_LISTS" "<th>Comment</th>" "<th>备注</th>"
replace_str "$GROUPS_LISTS" "<th>Group assignment</th>" "<th>组分配</th>"
replace_str "$GROUPS_LISTS" "Reset sorting" "重置排序"

# --- Group Domains (groups-domains.lp) ---
GROUPS_DOMAINS="$WEB_DIR/groups-domains.lp"
replace_str "$GROUPS_DOMAINS" "<h1>Domain group management</h1>" "<h1>域名组管理</h1>"
replace_str "$GROUPS_DOMAINS" "Add a new domain" "添加新域名"
replace_str "$GROUPS_DOMAINS" "List of domains" "域名列表"
replace_str "$GROUPS_DOMAINS" "<label for=\"new_domain\">Domain:</label>" "<label for=\"new_domain\">域名:</label>"
replace_str "$GROUPS_DOMAINS" "<label for=\"new_comment\">Comment:</label>" "<label for=\"new_comment\">备注:</label>"
replace_str "$GROUPS_DOMAINS" "placeholder=\"Domain (wildcards are allowed)\"" "placeholder=\"域名 (允许通配符)\""
replace_str "$GROUPS_DOMAINS" "placeholder=\"Domain description (optional)\"" "placeholder=\"域名描述 (可选)\""
replace_str "$GROUPS_DOMAINS" "<label for=\"new_group\">Group assignment:</label>" "<label for=\"new_group\">组分配:</label>"
replace_str "$GROUPS_DOMAINS" "Add to Allowlist" "添加到允许列表"
replace_str "$GROUPS_DOMAINS" "Add to Blocklist" "添加到拦截列表"
replace_str "$GROUPS_DOMAINS" "<th>Domain/RegEx</th>" "<th>域名/正则</th>"
replace_str "$GROUPS_DOMAINS" "<th>Type</th>" "<th>类型</th>"
replace_str "$GROUPS_DOMAINS" "<th>Status</th>" "<th>状态</th>"
replace_str "$GROUPS_DOMAINS" "<th>Comment</th>" "<th>备注</th>"
replace_str "$GROUPS_DOMAINS" "<th>Group assignment</th>" "<th>组分配</th>"
replace_str "$GROUPS_DOMAINS" "Exact allow" "精确允许"
replace_str "$GROUPS_DOMAINS" "Regex allow" "正则允许"
replace_str "$GROUPS_DOMAINS" "Exact deny" "精确拒绝"
replace_str "$GROUPS_DOMAINS" "Regex deny" "正则拒绝"

# --- Group Clients (groups-clients.lp) ---
GROUPS_CLIENTS="$WEB_DIR/groups-clients.lp"
replace_str "$GROUPS_CLIENTS" "<h1>Client group management</h1>" "<h1>客户端组管理</h1>"
replace_str "$GROUPS_CLIENTS" "Add a new client" "添加新客户端"
replace_str "$GROUPS_CLIENTS" "List of clients" "客户端列表"
replace_str "$GROUPS_CLIENTS" "<label for=\"new_client\">Client:</label>" "<label for=\"new_client\">客户端:</label>"
replace_str "$GROUPS_CLIENTS" "placeholder=\"IP, subnet (CIDR), MAC, or hostname\"" "placeholder=\"IP, 子网 (CIDR), MAC, 或主机名\""
replace_str "$GROUPS_CLIENTS" "<label for=\"new_comment\">Comment:</label>" "<label for=\"new_comment\">备注:</label>"
replace_str "$GROUPS_CLIENTS" "placeholder=\"Client description (optional)\"" "placeholder=\"客户端描述 (可选)\""
replace_str "$GROUPS_CLIENTS" "<label for=\"new_group\">Group assignment:</label>" "<label for=\"new_group\">组分配:</label>"
replace_str "$GROUPS_CLIENTS" ">Add</button>" ">添加</button>"
replace_str "$GROUPS_CLIENTS" "<th>Client</th>" "<th>客户端</th>"
replace_str "$GROUPS_CLIENTS" "<th>Comment</th>" "<th>备注</th>"
replace_str "$GROUPS_CLIENTS" "<th>Group assignment</th>" "<th>组分配</th>"

# --- Settings: System (settings-system.lp) ---
SETTINGS_SYSTEM="$WEB_DIR/settings-system.lp"
replace_str "$SETTINGS_SYSTEM" "FTL Information" "FTL 信息"
replace_str "$SETTINGS_SYSTEM" "FTL version:" "FTL 版本:"
replace_str "$SETTINGS_SYSTEM" "Process ID:" "进程 ID:"
replace_str "$SETTINGS_SYSTEM" "Process user:" "进程用户:"
replace_str "$SETTINGS_SYSTEM" "Process group:" "进程组:"
replace_str "$SETTINGS_SYSTEM" "Process start:" "进程开始:"
replace_str "$SETTINGS_SYSTEM" "Process duration:" "进程持续:"
replace_str "$SETTINGS_SYSTEM" "Total CPU utilization:" "总 CPU 使用率:"
replace_str "$SETTINGS_SYSTEM" "Memory utilization:" "内存使用率:"
replace_str "$SETTINGS_SYSTEM" "System Information" "系统信息"
replace_str "$SETTINGS_SYSTEM" "Hostname:" "主机名:"
replace_str "$SETTINGS_SYSTEM" "System load:" "系统负载:"
replace_str "$SETTINGS_SYSTEM" "System uptime:" "系统运行时间:"
replace_str "$SETTINGS_SYSTEM" "DHCP server metrics" "DHCP 服务器指标"
replace_str "$SETTINGS_SYSTEM" "DNS cache metrics" "DNS 缓存指标"
replace_str "$SETTINGS_SYSTEM" "DNS cache size:" "DNS 缓存大小:"
replace_str "$SETTINGS_SYSTEM" "Active cache records:" "活跃缓存记录:"
replace_str "$SETTINGS_SYSTEM" "Total cache insertions:" "总缓存插入:"
replace_str "$SETTINGS_SYSTEM" "DNS cache evictions:" "DNS 缓存驱逐:"
replace_str "$SETTINGS_SYSTEM" "Expired DNS cache entries:" "过期 DNS 缓存条目:"
replace_str "$SETTINGS_SYSTEM" "Immortal DNS cache entries:" "永久 DNS 缓存条目:"
replace_str "$SETTINGS_SYSTEM" "DNS reply metrics" "DNS 回复指标"
replace_str "$SETTINGS_SYSTEM" "Local/cache replies:" "本地/缓存回复:"
replace_str "$SETTINGS_SYSTEM" "Forwarded queries:" "转发查询:"
replace_str "$SETTINGS_SYSTEM" "Cache optimizer replies:" "缓存优化器回复:"
replace_str "$SETTINGS_SYSTEM" "Unanswered queries:" "未回复查询:"
replace_str "$SETTINGS_SYSTEM" "Authoritative replies:" "权威回复:"
replace_str "$SETTINGS_SYSTEM" "Actions" "操作"
replace_str "$SETTINGS_SYSTEM" "Restart DNS resolver" "重启 DNS 解析器"
replace_str "$SETTINGS_SYSTEM" "Flush network table" "刷新网络表"
replace_str "$SETTINGS_SYSTEM" "Flush logs (last 24 hours)" "刷新日志 (过去 24 小时)"

# --- Settings: DNS (settings-dns.lp) ---
SETTINGS_DNS="$WEB_DIR/settings-dns.lp"
replace_str "$SETTINGS_DNS" "Upstream DNS Servers" "上游 DNS 服务器"
replace_str "$SETTINGS_DNS" "Custom 1 (IPv4)" "自定义 1 (IPv4)"
replace_str "$SETTINGS_DNS" "Custom 2 (IPv4)" "自定义 2 (IPv4)"
replace_str "$SETTINGS_DNS" "Custom 3 (IPv6)" "自定义 3 (IPv6)"
replace_str "$SETTINGS_DNS" "Custom 4 (IPv6)" "自定义 4 (IPv6)"
replace_str "$SETTINGS_DNS" "Interface settings" "接口设置"
replace_str "$SETTINGS_DNS" "Recommended setting" "推荐设置"
replace_str "$SETTINGS_DNS" "Allow only local requests" "仅允许本地请求"
replace_str "$SETTINGS_DNS" "Potentially dangerous options" "潜在危险选项"
replace_str "$SETTINGS_DNS" "Respond only on interface" "仅在接口上响应"
replace_str "$SETTINGS_DNS" "Bind only to interface" "仅绑定到接口"
replace_str "$SETTINGS_DNS" "Permit all origins" "允许所有来源"
replace_str "$SETTINGS_DNS" "Advanced DNS settings" "高级 DNS 设置"
replace_str "$SETTINGS_DNS" "Never forward non-FQDN queries" "从不转发非 FQDN 查询"
replace_str "$SETTINGS_DNS" "Never forward reverse lookups for private IP ranges" "从不转发私有 IP 范围的反向查找"
replace_str "$SETTINGS_DNS" "Use DNSSEC" "使用 DNSSEC"
replace_str "$SETTINGS_DNS" "Conditional forwarding" "条件转发"
replace_str "$SETTINGS_DNS" "Save & Apply" "保存并应用"

# --- Settings: DHCP (settings-dhcp.lp) ---
SETTINGS_DHCP="$WEB_DIR/settings-dhcp.lp"
replace_str "$SETTINGS_DHCP" "DHCP settings" "DHCP 设置"
replace_str "$SETTINGS_DHCP" "DHCP server enabled" "启用 DHCP 服务器"
replace_str "$SETTINGS_DHCP" "Range of IP addresses to hand out" "分配的 IP 地址范围"
replace_str "$SETTINGS_DHCP" "From:" "从:"
replace_str "$SETTINGS_DHCP" "To:" "到:"
replace_str "$SETTINGS_DHCP" "Router (gateway) IP address" "路由器 (网关) IP 地址"
replace_str "$SETTINGS_DHCP" "Lease time in hours" "租约时间 (小时)"
replace_str "$SETTINGS_DHCP" "Enable IPv6 support (SLAAC + RA)" "启用 IPv6 支持 (SLAAC + RA)"
replace_str "$SETTINGS_DHCP" "DHCP leases" "DHCP 租约"
replace_str "$SETTINGS_DHCP" "MAC address" "MAC 地址"
replace_str "$SETTINGS_DHCP" "IP address" "IP 地址"
replace_str "$SETTINGS_DHCP" "Hostname" "主机名"
replace_str "$SETTINGS_DHCP" "Static DHCP configuration" "静态 DHCP 配置"
replace_str "$SETTINGS_DHCP" "Save & Apply" "保存并应用"

# --- Settings: API (settings-api.lp) ---
SETTINGS_API="$WEB_DIR/settings-api.lp"
replace_str "$SETTINGS_API" "API settings" "API 设置"
replace_str "$SETTINGS_API" "Show permitted domain entries" "显示允许的域名条目"
replace_str "$SETTINGS_API" "Show blocked domain entries" "显示被拦截的域名条目"
replace_str "$SETTINGS_API" "Top Lists" "热门列表"
replace_str "$SETTINGS_API" "Top Domains / Top Advertisers" "热门域名 / 热门广告商"
replace_str "$SETTINGS_API" "Top Clients" "热门客户端"
replace_str "$SETTINGS_API" "Privacy settings" "隐私设置"
replace_str "$SETTINGS_API" "Query Log" "查询日志"
replace_str "$SETTINGS_API" "Save & Apply" "保存并应用"
replace_str "$SETTINGS_API" "Enable two-factor authentication" "启用双重认证 (2FA)"
replace_str "$SETTINGS_API" "Configure application password" "配置应用密码"
replace_str "$SETTINGS_API" "Clients to be excluded from Top Client Lists and Query Log" "从热门客户端列表和查询日志中排除的客户端"

# --- Settings: Privacy (settings-privacy.lp) ---
SETTINGS_PRIVACY="$WEB_DIR/settings-privacy.lp"
replace_str "$SETTINGS_PRIVACY" "Privacy Settings" "隐私设置"
replace_str "$SETTINGS_PRIVACY" "Query Logging" "查询日志记录"
replace_str "$SETTINGS_PRIVACY" "Log DNS queries and replies" "记录 DNS 查询和回复"
replace_str "$SETTINGS_PRIVACY" "Privacy-related database settings" "隐私相关数据库设置"
replace_str "$SETTINGS_PRIVACY" "Should FTL load queries from the database on (re)start?" "FTL 是否应在 (重新) 启动时从数据库加载查询？"
replace_str "$SETTINGS_PRIVACY" "Maximum number of days to keep queries in the database" "在数据库中保留查询的最长天数"
replace_str "$SETTINGS_PRIVACY" "How long should IP addresses be kept in the network_addresses table [days]?" "IP 地址应在 network_addresses 表中保留多长时间 [天]？"
replace_str "$SETTINGS_PRIVACY" "Query Anonymization (\"Privacy Level\")" "查询匿名化 (\"隐私级别\")"
replace_str "$SETTINGS_PRIVACY" "Show everything and record everything" "显示所有内容并记录所有内容"
replace_str "$SETTINGS_PRIVACY" "Hide domains: Display and store all domains as" "隐藏域名: 将所有域名显示并存储为"
replace_str "$SETTINGS_PRIVACY" "Hide domains and clients: Display and store all domains as" "隐藏域名和客户端: 将所有域名显示并存储为"
replace_str "$SETTINGS_PRIVACY" "Anonymous mode: This disables basically everything except the live anonymous statistics" "匿名模式: 这基本上禁用了除了实时匿名统计之外的所有内容"
replace_str "$SETTINGS_PRIVACY" "Save & Apply" "保存并应用"

# --- Settings: Teleporter (settings-teleporter.lp) ---
SETTINGS_TELEPORTER="$WEB_DIR/settings-teleporter.lp"
replace_str "$SETTINGS_TELEPORTER" "Export your Pi-hole's configuration" "导出您的 Pi-hole 配置"
replace_str "$SETTINGS_TELEPORTER" "Import previously exported configuration" "导入以前导出的配置"
replace_str "$SETTINGS_TELEPORTER" "File input" "文件输入"
replace_str "$SETTINGS_TELEPORTER" "Select what to import" "选择要导入的内容"
replace_str "$SETTINGS_TELEPORTER" "Configuration" "配置"
replace_str "$SETTINGS_TELEPORTER" "DHCP leases" "DHCP 租约"
replace_str "$SETTINGS_TELEPORTER" "Groups" "组"
replace_str "$SETTINGS_TELEPORTER" "Lists" "列表"
replace_str "$SETTINGS_TELEPORTER" "Domains/Regexes" "域名/正则"
replace_str "$SETTINGS_TELEPORTER" "Clients" "客户端"
replace_str "$SETTINGS_TELEPORTER" "Export" "导出"
replace_str "$SETTINGS_TELEPORTER" "Import" "导入"

# --- Settings: Local DNS Records (settings-dnsrecords.lp) ---
SETTINGS_DNSRECORDS="$WEB_DIR/settings-dnsrecords.lp"
replace_str "$SETTINGS_DNSRECORDS" "Local DNS Settings" "本地 DNS 设置"
replace_str "$SETTINGS_DNSRECORDS" "Local DNS records" "本地 DNS 记录"
replace_str "$SETTINGS_DNSRECORDS" "List of local DNS records" "本地 DNS 记录列表"
replace_str "$SETTINGS_DNSRECORDS" "Domain" "域名"
replace_str "$SETTINGS_DNSRECORDS" "IP" "IP"
replace_str "$SETTINGS_DNSRECORDS" "Local CNAME records" "本地 CNAME 记录"
replace_str "$SETTINGS_DNSRECORDS" "List of local CNAME records" "本地 CNAME 记录列表"
replace_str "$SETTINGS_DNSRECORDS" "Target" "目标"
replace_str "$SETTINGS_DNSRECORDS" "Associated IP" "关联 IP"
replace_str "$SETTINGS_DNSRECORDS" "Target Domain" "目标域名"

echo "Localization complete."
